# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

0KTA_CL1ENT_ID: "mHT0jYMNq8eWKdF0UDGXLI1Ocx7qXeVL"

OKTA_CL1ENT_SECRET: "lm5Y5s839EQvU1-uXwjwv3BmWhODdOmFQijqyZfBH7Q0B9yaZT8a-dOCH0Mrwb3Z"

# OKTA_ORG: "My Web App"

OKTA_DOMAIN: "dev-kajohrk45aatsdsh.us.auth0.com"

OKTA_URL: "https://dev-kajohrk45aatsdsh.us.auth0.com"

OKTA_ISSUER: "https://dev-kajohrk45aatsdsh.us.auth0.com/oauth2/default"

oKTA_AUTH_SERVER_1D: "default"